package it.supermens.local

import android.text.Html
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.downloader.Downloader
import org.schabi.newpipe.extractor.downloader.Request
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.json.JSONObject
import android.util.Xml
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder
import org.xmlpull.v1.XmlPullParser

object YoutubeCaptions {
    data class VideoInfo(val title:String,val segments:List<Segment>,val reason:String="")
    private data class PlayerClient(val name:String,val version:String,val number:Int,val userAgent:String)
    private val playerClients=listOf(
        PlayerClient("IOS","21.26.4",5,"com.google.ios.youtube/21.26.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)"),
        PlayerClient("ANDROID","21.26.41",3,"com.google.android.youtube/21.26.41 (Linux; U; Android 15) gzip")
    )
    @Volatile private var initialized=false
    @Synchronized private fun init() {
        if(initialized) return
        NewPipe.init(object:Downloader() {
            override fun execute(request:Request):Response {
                val c=URL(request.url()).openConnection() as HttpURLConnection
                c.requestMethod=request.httpMethod(); c.connectTimeout=12000; c.readTimeout=20000
                request.headers()?.forEach { (name,values)-> values.forEach { c.addRequestProperty(name,it) } }
                if(c.getRequestProperty("User-Agent").isNullOrBlank()) c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 Chrome/131.0 Mobile Safari/537.36")
                request.dataToSend()?.let { c.doOutput=true; c.outputStream.use { out->out.write(it) } }
                val code=c.responseCode
                val body=(if(code in 200..299)c.inputStream else c.errorStream)?.bufferedReader()?.use { it.readText() } ?: ""
                val result=Response(code,c.responseMessage,c.headerFields.filterKeys { it!=null },body,c.url.toString())
                c.disconnect(); return result
            }
        })
        initialized=true
    }
    fun fetch(url:String,language:String="it"):VideoInfo {
        init()
        val info=StreamInfo.getInfo(url)
        val candidates=info.subtitles.sortedWith(compareBy({ !it.languageTag.startsWith("it") }, { !it.languageTag.startsWith("en") }, { it.extension !in listOf("vtt","srt") }, { it.isAutoGenerated })).take(6)
        var lastError=""
        for(candidate in candidates) {
            val parsed=runCatching {
                val content=if(candidate.isUrl) readText(candidate.content) else candidate.content
                parse(content)
            }.onFailure { lastError=it.message.orEmpty().take(100) }.getOrDefault(emptyList())
            if(parsed.isNotEmpty()) return VideoInfo(info.name,parsed.map { it.copy(source="caption:newpipe:${candidate.languageTag}${if(candidate.isAutoGenerated) ":auto" else ""}") })
        }
        return VideoInfo(info.name,emptyList(),if(candidates.isEmpty()) "video senza sottotitoli" else LanguageChoice.text(language,"sottotitoli non leggibili: $lastError","Unreadable captions: $lastError"))
    }
    fun fetchWithFallback(context:android.content.Context,url:String):VideoInfo {
        val language=AppLanguage.code(context)
        val videoId=videoId(url) ?: return VideoInfo("",emptyList(),LanguageChoice.text(language,"ID video non valido","Invalid video ID"))
        var knownTitle=""
        val errors=mutableListOf<String>()
        var noCaptionPlayers=0
        // This path also works when the watch page no longer contains ytInitialData.
        for(client in playerClients) {
            val result=runCatching { fetchPlayer(videoId,client,AppLanguage.code(context)) }
            if(result.isSuccess) {
                val found=result.getOrThrow()
                if(found.title.isNotBlank()) knownTitle=found.title
                if(found.segments.isNotEmpty()) return found
                if(found.reason=="video senza sottotitoli") noCaptionPlayers++
                errors += "${client.name}: ${found.reason}"
            } else errors += "${client.name}: ${result.exceptionOrNull()?.message ?: LanguageChoice.text(language,"errore di rete","Network error")}"
        }
        for(attempt in 0..1) {
            val result=runCatching { fetch(url,AppLanguage.code(context)) }
            if(result.isSuccess) {
                val found=result.getOrThrow()
                if(found.segments.isNotEmpty()) return found.copy(title=found.title.ifBlank { knownTitle })
                if(found.title.isNotBlank()) knownTitle=found.title
                errors += "NewPipe: ${found.reason}"
                break
            } else {
                val exception=result.exceptionOrNull()!!
                errors += "NewPipe: ${exception.message ?: exception.javaClass.simpleName}"
                if(exception !is java.io.IOException || attempt==1) break
            }
            if(attempt==0) Thread.sleep(400)
        }
        val instance=LocalPrefs.invidiousInstance(context)
        if(instance.isNotBlank()) {
            val fallback=runCatching { fetchInvidious(instance,url,AppLanguage.code(context)) }
            if(fallback.isSuccess) {
                val found=fallback.getOrThrow()
                if(found.segments.isNotEmpty()) return found.copy(title=knownTitle.ifBlank { found.title })
                errors += "Invidious: ${found.reason}"
            } else errors += "Invidious: ${fallback.exceptionOrNull()?.message.orEmpty()}"
        }
        val noCaptions=noCaptionPlayers==playerClients.size || (errors.isNotEmpty() && errors.all { it.endsWith("video senza sottotitoli") })
        return VideoInfo(knownTitle,emptyList(),if(noCaptions) "video senza sottotitoli" else errors.joinToString("; ").take(350))
    }
    internal fun videoId(url:String):String? {
        val parsed=runCatching { URL(url) }.getOrNull() ?: return null
        val host=parsed.host.lowercase()
        if(host!="youtu.be" && host!="youtube.com" && !host.endsWith(".youtube.com")) return null
        val id=if(host=="youtu.be") parsed.path.trim('/').substringBefore('/')
            else Regex("(?:^|&)v=([A-Za-z0-9_-]{11})(?:&|$)").find(parsed.query.orEmpty())?.groupValues?.get(1)
                ?: Regex("^/(?:shorts|live|embed)/([A-Za-z0-9_-]{11})(?:/|$)").find(parsed.path)?.groupValues?.get(1)
        return id?.takeIf { it.matches(Regex("[A-Za-z0-9_-]{11}")) }
    }
    private fun fetchPlayer(videoId:String,client:PlayerClient,language:String):VideoInfo {
        val request=JSONObject().put("context",JSONObject().put("client",JSONObject()
            .put("clientName",client.name).put("clientVersion",client.version).put("hl","en").put("gl","US")))
            .put("videoId",videoId).put("contentCheckOk",true).put("racyCheckOk",true)
        val connection=URL("https://www.youtube.com/youtubei/v1/player").openConnection() as HttpURLConnection
        connection.requestMethod="POST";connection.doOutput=true;connection.connectTimeout=12000;connection.readTimeout=20000
        connection.setRequestProperty("Content-Type","application/json")
        connection.setRequestProperty("User-Agent",client.userAgent)
        connection.setRequestProperty("X-YouTube-Client-Name",client.number.toString())
        connection.setRequestProperty("X-YouTube-Client-Version",client.version)
        val raw=try {
            connection.outputStream.use { it.write(request.toString().toByteArray(Charsets.UTF_8)) }
            val code=connection.responseCode
            if(code !in 200..299) error("HTTP $code")
            connection.inputStream.bufferedReader().use { it.readText().take(3_000_000) }
        } finally { connection.disconnect() }
        val data=JSONObject(raw)
        val title=data.optJSONObject("videoDetails")?.optString("title").orEmpty()
        val tracks=data.optJSONObject("captions")?.optJSONObject("playerCaptionsTracklistRenderer")?.optJSONArray("captionTracks")
        if(tracks==null || tracks.length()==0) {
            val status=data.optJSONObject("playabilityStatus")?.optString("status").orEmpty()
            return VideoInfo(title,emptyList(),if(status=="OK") "video senza sottotitoli" else LanguageChoice.text(language,"video non accessibile: $status","Video unavailable: $status"))
        }
        val ranked=(0 until tracks.length()).map { tracks.getJSONObject(it) }.sortedWith(compareBy(
            { !it.optString("languageCode").startsWith("it") },
            { !it.optString("languageCode").startsWith("en") },
            { it.optString("kind")=="asr" }
        )).take(8)
        val errors=mutableListOf<String>()
        for(track in ranked) {
            val address=track.optString("baseUrl")
            val addressUrl=runCatching { URL(address) }.getOrNull()
            val host=addressUrl?.host?.lowercase().orEmpty()
            if(addressUrl?.protocol!="https" || (host!="youtube.com" && !host.endsWith(".youtube.com"))) { errors += LanguageChoice.text(language,"URL sottotitoli non valido","Invalid caption URL");continue }
            val captionLanguage=track.optString("languageCode")
            val content=runCatching { readText(address+if(address.contains('?')) "&fmt=vtt" else "?fmt=vtt") }
                .onFailure { errors += it.message ?: LanguageChoice.text(language,"download fallito","Download failed") }.getOrNull() ?: continue
            if(content.isBlank()) { errors += LanguageChoice.text(language,"traccia $captionLanguage vuota (possibile blocco YouTube)","Empty $captionLanguage track (possible YouTube restriction)");continue }
            val parsed=parse(content).ifEmpty { parseTimedText(content) }
            if(parsed.isNotEmpty()) return VideoInfo(title,parsed.map { it.copy(source="caption:youtube-${client.name.lowercase()}:$captionLanguage${if(track.optString("kind")=="asr") ":auto" else ""}") })
            errors += LanguageChoice.text(language,"traccia $captionLanguage non leggibile","Unreadable $captionLanguage track")
        }
        return VideoInfo(title,emptyList(),errors.distinct().joinToString(", ").take(130))
    }
    private fun parseTimedText(raw:String):List<Segment> {
        if(!raw.trimStart().startsWith("<?xml") && !raw.trimStart().startsWith("<timedtext")) return emptyList()
        val parser=Xml.newPullParser()
        parser.setInput(raw.reader())
        val result=mutableListOf<Segment>()
        var start=-1L
        var content=StringBuilder()
        while(parser.eventType!=XmlPullParser.END_DOCUMENT) {
            when(parser.eventType) {
                XmlPullParser.START_TAG -> if(parser.name=="p" || parser.name=="text") {
                    start=parser.getAttributeValue(null,"t")?.toLongOrNull()
                        ?: parser.getAttributeValue(null,"start")?.toDoubleOrNull()?.times(1000)?.toLong() ?: -1L
                    content=StringBuilder()
                }
                XmlPullParser.TEXT -> if(start>=0) content.append(parser.text)
                XmlPullParser.END_TAG -> if((parser.name=="p" || parser.name=="text") && start>=0) {
                    val line=content.toString().trim()
                    if(line.isNotBlank()) result += Segment(0,"",line,start,-1,"caption")
                    start=-1L
                }
            }
            parser.next()
        }
        return result.distinctBy { it.startMs to it.text }
    }
    private fun fetchInvidious(instance:String,url:String,language:String):VideoInfo {
        val videoId=videoId(url) ?: error(LanguageChoice.text(language,"ID video non valido","Invalid video ID"))
        val endpoint="$instance/api/v1/captions/$videoId"
        val catalog=JSONObject(readText(endpoint)).getJSONArray("captions")
        val tracks=(0 until catalog.length()).map { catalog.getJSONObject(it) }.sortedWith(compareBy({ !it.optString("languageCode").startsWith("it") }, { !it.optString("languageCode").startsWith("en") })).take(6)
        if(tracks.isEmpty()) return VideoInfo("",emptyList(),"video senza sottotitoli")
        var lastError=""
        tracks.forEach { track ->
            val label=track.optString("label")
            val captionLanguage=track.optString("languageCode")
            val query=if(label.isNotBlank()) "label=${URLEncoder.encode(label,"UTF-8")}" else "lang=${URLEncoder.encode(captionLanguage,"UTF-8")}"
            val parsed=runCatching { parse(readText("$endpoint?$query").also { if(it.isBlank()) error(LanguageChoice.text(language,"risposta vuota","Empty response")) }) }.onFailure {lastError=it.message.orEmpty()}.getOrDefault(emptyList())
            if(parsed.isNotEmpty()) return VideoInfo("",parsed.map { it.copy(source="caption:invidious:$captionLanguage${if(label.contains("auto",true)) ":auto" else ""}") })
        }
        return VideoInfo("",emptyList(),LanguageChoice.text(language,"sottotitoli Invidious non leggibili: $lastError","Unreadable Invidious captions: $lastError"))
    }
    private fun readText(address:String):String {
        val connection=URL(address).openConnection() as HttpURLConnection
        connection.connectTimeout=12000;connection.readTimeout=20000
        try {
            if(connection.responseCode !in 200..299) error("HTTP ${connection.responseCode}")
            return connection.inputStream.bufferedReader().use { it.readText().take(3_000_000) }
        } finally { connection.disconnect() }
    }
    fun parse(raw:String):List<Segment> {
        val blocks=raw.replace("\r\n","\n").split(Regex("\n\\s*\n"))
        val result=mutableListOf<Segment>()
        val time=Regex("(\\d{1,2}:)?(\\d{2}):(\\d{2})[.,](\\d{3})\\s*-->.*")
        for(block in blocks) {
            val lines=block.lines().map { it.trim() }.filter { it.isNotBlank() }
            val index=lines.indexOfFirst { time.matches(it) }
            if(index<0 || index==lines.lastIndex) continue
            val m=time.matchEntire(lines[index]) ?: continue
            val hours=m.groupValues[1].removeSuffix(":").toLongOrNull() ?: 0
            val min=m.groupValues[2].toLong(); val sec=m.groupValues[3].toLong(); val milli=m.groupValues[4].toLong()
            val text=Html.fromHtml(lines.drop(index+1).joinToString(" ").replace(Regex("<[^>]+>"),""),Html.FROM_HTML_MODE_LEGACY).toString().trim()
            if(text.isNotBlank()) result+=Segment(0,"",text,((hours*3600+min*60+sec)*1000+milli),-1,"caption")
        }
        return result.distinctBy { it.startMs to it.text }
    }
}
